name: ai
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - matplotlib
  - plotly
  - sqlalchemy
  - jupyterlab
  - pip
  - pip:
      - streamlit
      - pandas-downcast