name: machine-learning
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - numpy
  - pandas
  - scikit-learn
  - optuna
  - plotly
  - scipy
  - pip
  - pip:
      - streamlit
      - botorch
      - python-constraint